language: python

cache: pip

sudo: required

dist: trusty

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"

install:
    - git clone https://github.com/kkos/oniguruma
    - pushd oniguruma
    - autoreconf -vfi
    - ./configure
    - make
    - sudo make install
    - popd
    - git clone https://github.com/stedolan/jq.git
    - pushd jq
    - autoreconf -i
    - ./configure --disable-maintainer-mode
    - make
    - sudo make install
    - popd

script:
    - python via4cve.py
